swagger: '2.0'
info:
  version: "1.0.0"
  title: Credit-api
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /dishes:
    # binds a127 app logic to a route
    x-swagger-router-controller: get_dishes
    get:
      description: Список блюд
      # used as the method name of the controller
      operationId: getDishes
      parameters:
        - name: Филадельфия
          in: query
          description: cost $20 
          required: false
          type: string
        - name: Калифорния  
          in: query
          description: cost $15
          required: false
          type: string
        - name: Нью-Йорк 
          in: query
          description: cost $19 
          required: false
          type: string
        - name: Цезарь
          in: query
          description: cost $25
          required: false
          type: string  
        - name: Оливье
          in: query
          description: cost $13 
          required: false
          type: string   
        - name: Селедка под шубой
          in: query
          description: cost $18 
          required: false
          type: string  
        - name: Маргарита
          in: query
          description: cost $17 
          required: false
          type: string 
        - name: 4 Сыра
          in: query
          description: cost $28 
          required: false
          type: string 
        - name: Пеперони
          in: query
          description: cost $21 
          required: false
          type: string 
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Jimuse-configureResponse"
        # responses may fall through to errors
        "500":
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Jimuse-configureResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string