swagger: "2.0"
info:
  version: "0.0.1"
  title: Credit App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /api/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /products:
    # binds a127 app logic to a route
    x-swagger-router-controller: get_products
    get:
      description: List of products
      # used as the method name of the controller
      operationId: getProducts
      parameters:
        - name: name
          in: query
          description: The name of goods on the page
          type: string
        - name: pageSize
          in: query
          description: Number of products returned
          type: number
          format: integer
        - name: pageNumber
          in: query
          description: Page number
          type: number
          format: integer
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
             $ref: "#/definitions/Product"
        # responses may fall through to errors
            
  /products/{productId}:
  # binds a127 app logic to a route
   x-swagger-router-controller: get_product
   get:
    summary: Gets a certain product
    description: Single product for its ID
    operationId: getProduct
    parameters:
     - name: productId
       in: path
       required: true
       description: The product's id
       type: string
    responses:
     200:
      description: A Product
      schema:
       $ref: "#/definitions/Product"
     404:
      description: The product does not exists.
  /swagger:
   x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
 Product:
  type: object
  properties:
   name:
    type: string
    description: Short name of the product
   description:
    type: string
    description: Full description of the product
   price:
    type: number
    format: float
    description: Price in a given currency
   place:
    type: string
    description: Place where this product is served
   data:
    type: number
    format: float
    description: Time when the product was added to the site
   image:
    type: string
    description: Image URL representing the product.
   like:
    type: number
    format: float
    description: Product evaluation
 Error:
    required:
      - message
    properties:
      message:
        type: string
